# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaEkran(object):
    def setupUi(self, AnaEkran):
        AnaEkran.setObjectName("AnaEkran")
        AnaEkran.resize(800, 600)
        self.AnaForm = QtWidgets.QWidget(AnaEkran)
        self.AnaForm.setObjectName("AnaForm")
        self.tableWidget = QtWidgets.QTableWidget(self.AnaForm)
        self.tableWidget.setGeometry(QtCore.QRect(40, 30, 731, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        AnaEkran.setCentralWidget(self.AnaForm)
        self.menubar = QtWidgets.QMenuBar(AnaEkran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuKitap_Listesi = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Listesi.setObjectName("menuKitap_Listesi")
        self.menuKitap_Ekle = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Ekle.setObjectName("menuKitap_Ekle")
        self.menuKitap_Guncelle = QtWidgets.QMenu(self.menubar)
        self.menuKitap_Guncelle.setObjectName("menuKitap_Guncelle")
        self.menuSil = QtWidgets.QMenu(self.menubar)
        self.menuSil.setObjectName("menuSil")
        self.menuCikis = QtWidgets.QMenu(self.menubar)
        self.menuCikis.setObjectName("menuCikis")
        AnaEkran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnaEkran)
        self.statusbar.setObjectName("statusbar")
        AnaEkran.setStatusBar(self.statusbar)
        self.actionKitap_Ekle = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Ekle.setObjectName("actionKitap_Ekle")
        self.actionKitap_Listele = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Listele.setObjectName("actionKitap_Listele")
        self.actionKitap_G_ncelle = QtWidgets.QAction(AnaEkran)
        self.actionKitap_G_ncelle.setObjectName("actionKitap_G_ncelle")
        self.actionKitap_Sil = QtWidgets.QAction(AnaEkran)
        self.actionKitap_Sil.setObjectName("actionKitap_Sil")
        self.menuKitap_Listesi.addAction(self.actionKitap_Listele)
        self.menuKitap_Ekle.addAction(self.actionKitap_Ekle)
        self.menuKitap_Guncelle.addAction(self.actionKitap_G_ncelle)
        self.menuSil.addAction(self.actionKitap_Sil)
        self.menubar.addAction(self.menuKitap_Listesi.menuAction())
        self.menubar.addAction(self.menuKitap_Ekle.menuAction())
        self.menubar.addAction(self.menuKitap_Guncelle.menuAction())
        self.menubar.addAction(self.menuSil.menuAction())
        self.menubar.addAction(self.menuCikis.menuAction())

        self.retranslateUi(AnaEkran)
        QtCore.QMetaObject.connectSlotsByName(AnaEkran)

    def retranslateUi(self, AnaEkran):
        _translate = QtCore.QCoreApplication.translate
        AnaEkran.setWindowTitle(_translate("AnaEkran", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AnaEkran", "Kitap ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AnaEkran", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AnaEkran", "Kitap Yazarı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AnaEkran", "Okunma Durumu"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AnaEkran", "Beğeni Durumu"))
        self.menuKitap_Listesi.setTitle(_translate("AnaEkran", "Kitap Listesi"))
        self.menuKitap_Ekle.setTitle(_translate("AnaEkran", "Kitap Ekle"))
        self.menuKitap_Guncelle.setTitle(_translate("AnaEkran", "Kitap Güncelle"))
        self.menuSil.setTitle(_translate("AnaEkran", "Sil"))
        self.menuCikis.setTitle(_translate("AnaEkran", "Çıkış"))
        self.actionKitap_Ekle.setText(_translate("AnaEkran", "Kitap Ekle"))
        self.actionKitap_Listele.setText(_translate("AnaEkran", "Kitap Listele"))
        self.actionKitap_G_ncelle.setText(_translate("AnaEkran", "Kitap Güncelle"))
        self.actionKitap_Sil.setText(_translate("AnaEkran", "Kitap Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnaEkran = QtWidgets.QMainWindow()
    ui = Ui_AnaEkran()
    ui.setupUi(AnaEkran)
    AnaEkran.show()
    sys.exit(app.exec_())
